/* src/components/SeoFaq.tsx */

export function SeoFaq() {
    return (
        <section className="seoFaq" aria-labelledby="seo-faq-title">
            <div className="seoFaqHeader">

                <h2 id="seo-faq-title">
                    Common questions about underground leak adjustments
                </h2>

                <p>
                    This helper prepares a PDF packet for the Miami-Dade
                    Underground or Concealed Leak Adjustment Request. It does
                    not submit the request for you.
                </p>
            </div>

            <div className="seoFaqGrid">
                <article>
                    <h3>What does this app help me do?</h3>
                    <p>
                        It helps you fill out the official Miami-Dade underground
                        or concealed leak adjustment request, add repair photos
                        and documents, sign the form, and download one PDF
                        packet.
                    </p>
                </article>

                <article>
                    <h3>Is this app Miami-Dade County?</h3>
                    <p>
                        No. This is an independent helper. Miami-Dade Water and
                        Sewer Department reviews the request after you submit it.
                    </p>
                </article>

                <article>
                    <h3>What documents should I include?</h3>
                    <p>
                        You should include the completed signed form generated by this tool,
                        a repair invoice or repair statement, and before and after photos
                        of the plumbing repair.
                    </p>
                </article>

                <article>
                    <h3>Where do I submit the completed packet?</h3>
                    <p>
                        The official form lists the submission email as
                        WASD-CreditRequest@miamidade.gov. You can also review
                        the form instructions before sending.
                    </p>
                </article>

                <article>
                    <h3>Does this app store my information?</h3>
                    <p>
                        Your draft, signature, photos, and documents stay in
                        your browser. They are not uploaded to a server by this
                        app.
                    </p>
                </article>

                <article>
                    <h3>Can approval be guaranteed?</h3>
                    <p>
                        No. This app only helps prepare the request packet.
                        Miami-Dade decides whether an adjustment is approved.
                    </p>
                </article>
            </div>
        </section>
    )
}